set fenc=utf-8
set fencs=utf-8,usc-bom,euc-jp,gb18030,gbk,gb2312,cp936

set nocompatible
syntax on

set tabstop=4
set shiftwidth=4
set expandtab

set nu

set nowrap

set hlsearch
set incsearch

behave mswin
colo slate
set nobackup
set autoindent
set cindent
set ic
set cursorline
set wildmenu

set whichwrap+=<,>,h,l
set autoread


"Paste toggle - when pasting something in, don't indent.
set pastetoggle=<F3>

"Remove indenting on empty lines
map <F2> :%s/\s*$//g<cr>:noh<cr>''

"folding settings
set foldmethod=indent   "fold based on indent
set foldenable

map <space> /

map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l

map <M-k> :move .-2<CR>
map <M-j> :move .+1<CR>

map <C-t> <ESC>:tabnew .<CR>

func! DeleteTrailingWS()
  exe "normal mz"
  %s/\s\+$//ge
  exe "normal `z"
endfunc

autocmd BufWrite *.py :call DeleteTrailingWS()

"Set for taglist
filetype plugin on
let Tlist_Use_Right_Window=1
let Tlist_File_Fold_Auto_Close=1
let Tlist_Auto_Open=1
